name: CI
on: 
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
        os: [windows-latest, ubuntu-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3.0.2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4.1.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        run: |
          pipx install poetry
          poetry --version
      - name: Build tap on Python ${{ matrix.python-version }} 
        run: |
          poetry env use purposelyfail
