name: CI
on: 
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry==1.1.14
      - name: Build tap on Python ${{ matrix.python-version }} 
        run: |
          poetry build
          poetry env use ${{ matrix.python-version }}
